# Generated by Django 5.0.6 on 2024-05-28 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGenero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DondeVer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plataforma', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FotosPerfil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Critica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('sipnosis', models.TextField()),
                ('link_trailer', models.URLField()),
                ('nombre_espanol', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('escritor', models.CharField(max_length=100)),
                ('reparto', models.TextField()),
                ('ano', models.IntegerField()),
                ('pais', models.CharField(max_length=100)),
                ('no_capitulos', models.IntegerField()),
                ('critica', models.TextField()),
                ('categoria_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.categoriagenero')),
                ('donde_ver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.dondever')),
                ('id_foto_critica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.fotosperfil')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='FotosCritica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('critica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.critica')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('correo', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('permisos', models.CharField(max_length=50)),
                ('foto_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.fotosperfil')),
            ],
        ),
    ]
