# Generated by Django 5.0.6 on 2024-05-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_user_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='foto_perfil',
        ),
        migrations.AddField(
            model_name='user',
            name='direccion_foto_perfil',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
