# Generated by Django 5.0.6 on 2024-05-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_user_foto_perfil_user_direccion_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='direccion_foto_perfil',
        ),
        migrations.AddField(
            model_name='user',
            name='foto_perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.fotosperfil'),
            preserve_default=False,
        ),
    ]
