# Generated by Django 5.0.6 on 2024-05-29 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_user_direccion_foto_perfil_user_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='permisos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.permisos'),
        ),
    ]
