# Generated by Django 5.0.6 on 2024-05-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_fotosperfil_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critica',
            name='categoria_genero',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='critica',
            name='donde_ver',
            field=models.CharField(max_length=200),
        ),
    ]
