# Generated by Django 5.0.6 on 2024-05-31 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_critica_datetime_critica_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='critica',
            old_name='user_id',
            new_name='user',
        ),
    ]
