# Generated by Django 5.0.6 on 2024-06-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_rename_user_id_critica_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='critica',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
