# Generated by Django 5.0.6 on 2024-06-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_critica_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critica',
            name='calificacion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
