# Generated by Django 5.0.6 on 2024-07-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critica',
            name='link_trailer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
